name: Node.js CI

on:
  push:
    branches: [ master, dev, ci ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x, 14.x, 16.x]
        python-version: [3.9, 3.8, 3.7, 3.6]

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node: ${{ matrix.node-version }}
        cache: npm

    - name: Use Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python: ${{ matrix.python-version }}

    - name: Install dependencies
      run: npm ci

    - name: Run test suite
      run: npm test

    - name: Log coverage
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
