name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12.x, 14.x, 16.x]
        python: [3.9]

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node: ${{ matrix.node }}
        cache: npm

    - name: Use Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python: ${{ matrix.python }}

    - name: Install dependencies
      run: npm ci

    - name: Run test suite
      run: npm test

    - name: Log coverage
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
